name: 比较影片差异

on:
  workflow_dispatch:
    inputs:
      release_tag_1:
        description: '第一个发行版标签 (如 v1.0.0)'
        required: true
        default: 'v1.0.0'
      release_tag_2:
        description: '第二个发行版标签 (如 v2.0.0)'
        required: true
        default: 'v2.0.0'

jobs:
  compare-mp4:
    runs-on: ubuntu-latest
    env:
      LANG: zh-CN.UTF-8
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 下载第一个发行版的 MP4 文件（1.mp4）
        run: |
          chmod +x download.sh
          ./download.sh ${{ inputs.release_tag_1 }} 1.mp4

      - name: 下载第二个发行版的 MP4 文件（2.mp4）
        run: |
          chmod +x download.sh
          ./download.sh ${{ inputs.release_tag_2 }} 2.mp4

      - name: 检查文件是否存在
        run: |
          if [ ! -f "1.mp4" ]; then
            echo "第一个发行版未找到 1.mp4"
            exit 1
          fi
          if [ ! -f "2.mp4" ]; then
            echo "第二个发行版未找到 2.mp4"
            exit 1
          fi

      - name: 安装 Bento4（包含 mp4dump）
        run: |
          wget https://www.bok.net/Bento4/binaries/Bento4-SDK-1-6-0-641.x86_64-unknown-linux.zip
          unzip Bento4-SDK-1-6-0-641.x86_64-unknown-linux.zip -d bento4
          export PATH=$PATH:$(pwd)/bento4/bin

      - name: 检查 mp4dump 安装路径
        run: |
          which mp4dump || { echo "mp4dump 未安装"; exit 1; }

      - name: 结构化比较 MP4 文件
        run: |
          ./bento4/bin/mp4dump 1.mp4 > 1.txt
          ./bento4/bin/mp4dump 2.mp4 > 2.txt
          diff 1.txt 2.txt > mp4_diff_result.txt || true
          cat mp4_diff_result.txt

      - name: 上传比较结果
        uses: actions/upload-artifact@v4
        with:
          name: mp4-diff-result
          path: mp4_diff_result.txt